//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_Ly_Thi.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-4RNGLB2\\SQLEXPRESS;Initial Catalog=QuanLyThiTracNghiemDB;User" +
            " ID=sa;Password=tuananh1")]
        public string QuanLyThiTracNghiemDBConnectionString {
            get {
                return ((string)(this["QuanLyThiTracNghiemDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-Q4DBGD9\\SQLEXPRESS;Initial Catalog=QuanLyThiTracNghiemDB;User" +
            " ID=sa;Password=1908")]
        public string QuanLyThiTracNghiemDBConnectionString1 {
            get {
                return ((string)(this["QuanLyThiTracNghiemDBConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-PD2UJ9U;Initial Catalog=QuanLyThiTracNghiemDB;Persist Securit" +
            "y Info=True;User ID=sa;Password=Thedao032")]
        public string QuanLyThiTracNghiemDBConnectionString3 {
            get {
                return ((string)(this["QuanLyThiTracNghiemDBConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-PD2UJ9U;Initial Catalog=QuanLyThiTracNghiemDB;Persist Securit" +
            "y Info=True;User ID=sa;Password=Thedao032")]
        public string QuanLyThiTracNghiemDBConnectionString2 {
            get {
                return ((string)(this["QuanLyThiTracNghiemDBConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-4RNGLB2\\SQLEXPRESS;Initial Catalog=QuanLyThiTracNghiemDB;Pers" +
            "ist Security Info=True;User ID=sa;Password=tuananh1")]
        public string QuanLyThiTracNghiemDBConnectionString4 {
            get {
                return ((string)(this["QuanLyThiTracNghiemDBConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-HQM5AIL;Initial Catalog=QuanLyThiTracNghiemDB;Integrated Secu" +
            "rity=True")]
        public string QuanLyThiTracNghiemDBConnectionString5 {
            get {
                return ((string)(this["QuanLyThiTracNghiemDBConnectionString5"]));
            }
        }
    }
}
