#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_Ly_Thi.DAO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyThiTracNghiemDB")]
	public partial class QLTTNDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCAPDOCAUHOI(CAPDOCAUHOI instance);
    partial void UpdateCAPDOCAUHOI(CAPDOCAUHOI instance);
    partial void DeleteCAPDOCAUHOI(CAPDOCAUHOI instance);
    partial void InsertPHANQUYEN(PHANQUYEN instance);
    partial void UpdatePHANQUYEN(PHANQUYEN instance);
    partial void DeletePHANQUYEN(PHANQUYEN instance);
    partial void InsertCAUHOI(CAUHOI instance);
    partial void UpdateCAUHOI(CAUHOI instance);
    partial void DeleteCAUHOI(CAUHOI instance);
    partial void InsertCHITIETDETHI(CHITIETDETHI instance);
    partial void UpdateCHITIETDETHI(CHITIETDETHI instance);
    partial void DeleteCHITIETDETHI(CHITIETDETHI instance);
    partial void InsertCHITIETKYTHI(CHITIETKYTHI instance);
    partial void UpdateCHITIETKYTHI(CHITIETKYTHI instance);
    partial void DeleteCHITIETKYTHI(CHITIETKYTHI instance);
    partial void InsertDANHSACHTHISINH(DANHSACHTHISINH instance);
    partial void UpdateDANHSACHTHISINH(DANHSACHTHISINH instance);
    partial void DeleteDANHSACHTHISINH(DANHSACHTHISINH instance);
    partial void InsertDETHI(DETHI instance);
    partial void UpdateDETHI(DETHI instance);
    partial void DeleteDETHI(DETHI instance);
    partial void InsertKETQUATHI(KETQUATHI instance);
    partial void UpdateKETQUATHI(KETQUATHI instance);
    partial void DeleteKETQUATHI(KETQUATHI instance);
    partial void InsertKHOI(KHOI instance);
    partial void UpdateKHOI(KHOI instance);
    partial void DeleteKHOI(KHOI instance);
    partial void InsertKYTHI(KYTHI instance);
    partial void UpdateKYTHI(KYTHI instance);
    partial void DeleteKYTHI(KYTHI instance);
    partial void InsertLOAICAUHOI(LOAICAUHOI instance);
    partial void UpdateLOAICAUHOI(LOAICAUHOI instance);
    partial void DeleteLOAICAUHOI(LOAICAUHOI instance);
    partial void InsertLOAIKYTHI(LOAIKYTHI instance);
    partial void UpdateLOAIKYTHI(LOAIKYTHI instance);
    partial void DeleteLOAIKYTHI(LOAIKYTHI instance);
    partial void InsertLOPHOC(LOPHOC instance);
    partial void UpdateLOPHOC(LOPHOC instance);
    partial void DeleteLOPHOC(LOPHOC instance);
    partial void InsertMONHOC(MONHOC instance);
    partial void UpdateMONHOC(MONHOC instance);
    partial void DeleteMONHOC(MONHOC instance);
    partial void InsertNGUOIDUNG(NGUOIDUNG instance);
    partial void UpdateNGUOIDUNG(NGUOIDUNG instance);
    partial void DeleteNGUOIDUNG(NGUOIDUNG instance);
    #endregion
		
		public QLTTNDataContext() : 
				base(global::Quan_Ly_Thi.Properties.Settings.Default.QuanLyThiTracNghiemDBConnectionString4, mappingSource)
		{
			OnCreated();
		}
		
		public QLTTNDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLTTNDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLTTNDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLTTNDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CAPDOCAUHOI> CAPDOCAUHOIs
		{
			get
			{
				return this.GetTable<CAPDOCAUHOI>();
			}
		}
		
		public System.Data.Linq.Table<PHANQUYEN> PHANQUYENs
		{
			get
			{
				return this.GetTable<PHANQUYEN>();
			}
		}
		
		public System.Data.Linq.Table<CAUHOI> CAUHOIs
		{
			get
			{
				return this.GetTable<CAUHOI>();
			}
		}
		
		public System.Data.Linq.Table<CHITIETDETHI> CHITIETDETHIs
		{
			get
			{
				return this.GetTable<CHITIETDETHI>();
			}
		}
		
		public System.Data.Linq.Table<CHITIETKYTHI> CHITIETKYTHIs
		{
			get
			{
				return this.GetTable<CHITIETKYTHI>();
			}
		}
		
		public System.Data.Linq.Table<DANHSACHTHISINH> DANHSACHTHISINHs
		{
			get
			{
				return this.GetTable<DANHSACHTHISINH>();
			}
		}
		
		public System.Data.Linq.Table<DETHI> DETHIs
		{
			get
			{
				return this.GetTable<DETHI>();
			}
		}
		
		public System.Data.Linq.Table<KETQUATHI> KETQUATHIs
		{
			get
			{
				return this.GetTable<KETQUATHI>();
			}
		}
		
		public System.Data.Linq.Table<KHOI> KHOIs
		{
			get
			{
				return this.GetTable<KHOI>();
			}
		}
		
		public System.Data.Linq.Table<KYTHI> KYTHIs
		{
			get
			{
				return this.GetTable<KYTHI>();
			}
		}
		
		public System.Data.Linq.Table<LOAICAUHOI> LOAICAUHOIs
		{
			get
			{
				return this.GetTable<LOAICAUHOI>();
			}
		}
		
		public System.Data.Linq.Table<LOAIKYTHI> LOAIKYTHIs
		{
			get
			{
				return this.GetTable<LOAIKYTHI>();
			}
		}
		
		public System.Data.Linq.Table<LOPHOC> LOPHOCs
		{
			get
			{
				return this.GetTable<LOPHOC>();
			}
		}
		
		public System.Data.Linq.Table<MONHOC> MONHOCs
		{
			get
			{
				return this.GetTable<MONHOC>();
			}
		}
		
		public System.Data.Linq.Table<NGUOIDUNG> NGUOIDUNGs
		{
			get
			{
				return this.GetTable<NGUOIDUNG>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CAPDOCAUHOI")]
	public partial class CAPDOCAUHOI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaCapDo;
		
		private string _TenCapDo;
		
		private EntitySet<CAUHOI> _CAUHOIs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCapDoChanging(string value);
    partial void OnMaCapDoChanged();
    partial void OnTenCapDoChanging(string value);
    partial void OnTenCapDoChanged();
    #endregion
		
		public CAPDOCAUHOI()
		{
			this._CAUHOIs = new EntitySet<CAUHOI>(new Action<CAUHOI>(this.attach_CAUHOIs), new Action<CAUHOI>(this.detach_CAUHOIs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCapDo", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaCapDo
		{
			get
			{
				return this._MaCapDo;
			}
			set
			{
				if ((this._MaCapDo != value))
				{
					this.OnMaCapDoChanging(value);
					this.SendPropertyChanging();
					this._MaCapDo = value;
					this.SendPropertyChanged("MaCapDo");
					this.OnMaCapDoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCapDo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenCapDo
		{
			get
			{
				return this._TenCapDo;
			}
			set
			{
				if ((this._TenCapDo != value))
				{
					this.OnTenCapDoChanging(value);
					this.SendPropertyChanging();
					this._TenCapDo = value;
					this.SendPropertyChanged("TenCapDo");
					this.OnTenCapDoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CAPDOCAUHOI_CAUHOI", Storage="_CAUHOIs", ThisKey="MaCapDo", OtherKey="MaCapDo")]
		public EntitySet<CAUHOI> CAUHOIs
		{
			get
			{
				return this._CAUHOIs;
			}
			set
			{
				this._CAUHOIs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CAUHOIs(CAUHOI entity)
		{
			this.SendPropertyChanging();
			entity.CAPDOCAUHOI = this;
		}
		
		private void detach_CAUHOIs(CAUHOI entity)
		{
			this.SendPropertyChanging();
			entity.CAPDOCAUHOI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHANQUYEN")]
	public partial class PHANQUYEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPhanQuyen;
		
		private string _TenPhanQuyen;
		
		private EntitySet<NGUOIDUNG> _NGUOIDUNGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhanQuyenChanging(string value);
    partial void OnMaPhanQuyenChanged();
    partial void OnTenPhanQuyenChanging(string value);
    partial void OnTenPhanQuyenChanged();
    #endregion
		
		public PHANQUYEN()
		{
			this._NGUOIDUNGs = new EntitySet<NGUOIDUNG>(new Action<NGUOIDUNG>(this.attach_NGUOIDUNGs), new Action<NGUOIDUNG>(this.detach_NGUOIDUNGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhanQuyen", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPhanQuyen
		{
			get
			{
				return this._MaPhanQuyen;
			}
			set
			{
				if ((this._MaPhanQuyen != value))
				{
					this.OnMaPhanQuyenChanging(value);
					this.SendPropertyChanging();
					this._MaPhanQuyen = value;
					this.SendPropertyChanged("MaPhanQuyen");
					this.OnMaPhanQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPhanQuyen", DbType="NVarChar(50)")]
		public string TenPhanQuyen
		{
			get
			{
				return this._TenPhanQuyen;
			}
			set
			{
				if ((this._TenPhanQuyen != value))
				{
					this.OnTenPhanQuyenChanging(value);
					this.SendPropertyChanging();
					this._TenPhanQuyen = value;
					this.SendPropertyChanged("TenPhanQuyen");
					this.OnTenPhanQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHANQUYEN_NGUOIDUNG", Storage="_NGUOIDUNGs", ThisKey="MaPhanQuyen", OtherKey="MaPhanQuyen")]
		public EntitySet<NGUOIDUNG> NGUOIDUNGs
		{
			get
			{
				return this._NGUOIDUNGs;
			}
			set
			{
				this._NGUOIDUNGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NGUOIDUNGs(NGUOIDUNG entity)
		{
			this.SendPropertyChanging();
			entity.PHANQUYEN = this;
		}
		
		private void detach_NGUOIDUNGs(NGUOIDUNG entity)
		{
			this.SendPropertyChanging();
			entity.PHANQUYEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CAUHOI")]
	public partial class CAUHOI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaCauHoi;
		
		private string _MaLoaiCauHoi;
		
		private string _MaCapDo;
		
		private string _MaKhoi;
		
		private string _MaMonHoc;
		
		private string _CauHoi1;
		
		private string _CauA;
		
		private string _CauB;
		
		private string _CauC;
		
		private string _CauD;
		
		private string _GoiY;
		
		private string _DapAn;
		
		private EntitySet<CHITIETDETHI> _CHITIETDETHIs;
		
		private EntityRef<CAPDOCAUHOI> _CAPDOCAUHOI;
		
		private EntityRef<KHOI> _KHOI;
		
		private EntityRef<LOAICAUHOI> _LOAICAUHOI;
		
		private EntityRef<MONHOC> _MONHOC;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCauHoiChanging(string value);
    partial void OnMaCauHoiChanged();
    partial void OnMaLoaiCauHoiChanging(string value);
    partial void OnMaLoaiCauHoiChanged();
    partial void OnMaCapDoChanging(string value);
    partial void OnMaCapDoChanged();
    partial void OnMaKhoiChanging(string value);
    partial void OnMaKhoiChanged();
    partial void OnMaMonHocChanging(string value);
    partial void OnMaMonHocChanged();
    partial void OnCauHoi1Changing(string value);
    partial void OnCauHoi1Changed();
    partial void OnCauAChanging(string value);
    partial void OnCauAChanged();
    partial void OnCauBChanging(string value);
    partial void OnCauBChanged();
    partial void OnCauCChanging(string value);
    partial void OnCauCChanged();
    partial void OnCauDChanging(string value);
    partial void OnCauDChanged();
    partial void OnGoiYChanging(string value);
    partial void OnGoiYChanged();
    partial void OnDapAnChanging(string value);
    partial void OnDapAnChanged();
    #endregion
		
		public CAUHOI()
		{
			this._CHITIETDETHIs = new EntitySet<CHITIETDETHI>(new Action<CHITIETDETHI>(this.attach_CHITIETDETHIs), new Action<CHITIETDETHI>(this.detach_CHITIETDETHIs));
			this._CAPDOCAUHOI = default(EntityRef<CAPDOCAUHOI>);
			this._KHOI = default(EntityRef<KHOI>);
			this._LOAICAUHOI = default(EntityRef<LOAICAUHOI>);
			this._MONHOC = default(EntityRef<MONHOC>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCauHoi", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaCauHoi
		{
			get
			{
				return this._MaCauHoi;
			}
			set
			{
				if ((this._MaCauHoi != value))
				{
					this.OnMaCauHoiChanging(value);
					this.SendPropertyChanging();
					this._MaCauHoi = value;
					this.SendPropertyChanged("MaCauHoi");
					this.OnMaCauHoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiCauHoi", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MaLoaiCauHoi
		{
			get
			{
				return this._MaLoaiCauHoi;
			}
			set
			{
				if ((this._MaLoaiCauHoi != value))
				{
					if (this._LOAICAUHOI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiCauHoiChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiCauHoi = value;
					this.SendPropertyChanged("MaLoaiCauHoi");
					this.OnMaLoaiCauHoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCapDo", DbType="Char(10)")]
		public string MaCapDo
		{
			get
			{
				return this._MaCapDo;
			}
			set
			{
				if ((this._MaCapDo != value))
				{
					if (this._CAPDOCAUHOI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaCapDoChanging(value);
					this.SendPropertyChanging();
					this._MaCapDo = value;
					this.SendPropertyChanged("MaCapDo");
					this.OnMaCapDoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhoi", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MaKhoi
		{
			get
			{
				return this._MaKhoi;
			}
			set
			{
				if ((this._MaKhoi != value))
				{
					if (this._KHOI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhoiChanging(value);
					this.SendPropertyChanging();
					this._MaKhoi = value;
					this.SendPropertyChanged("MaKhoi");
					this.OnMaKhoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMonHoc", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MaMonHoc
		{
			get
			{
				return this._MaMonHoc;
			}
			set
			{
				if ((this._MaMonHoc != value))
				{
					if (this._MONHOC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaMonHocChanging(value);
					this.SendPropertyChanging();
					this._MaMonHoc = value;
					this.SendPropertyChanged("MaMonHoc");
					this.OnMaMonHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="CauHoi", Storage="_CauHoi1", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string CauHoi1
		{
			get
			{
				return this._CauHoi1;
			}
			set
			{
				if ((this._CauHoi1 != value))
				{
					this.OnCauHoi1Changing(value);
					this.SendPropertyChanging();
					this._CauHoi1 = value;
					this.SendPropertyChanged("CauHoi1");
					this.OnCauHoi1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CauA", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string CauA
		{
			get
			{
				return this._CauA;
			}
			set
			{
				if ((this._CauA != value))
				{
					this.OnCauAChanging(value);
					this.SendPropertyChanging();
					this._CauA = value;
					this.SendPropertyChanged("CauA");
					this.OnCauAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CauB", DbType="NVarChar(1000)")]
		public string CauB
		{
			get
			{
				return this._CauB;
			}
			set
			{
				if ((this._CauB != value))
				{
					this.OnCauBChanging(value);
					this.SendPropertyChanging();
					this._CauB = value;
					this.SendPropertyChanged("CauB");
					this.OnCauBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CauC", DbType="NVarChar(1000)")]
		public string CauC
		{
			get
			{
				return this._CauC;
			}
			set
			{
				if ((this._CauC != value))
				{
					this.OnCauCChanging(value);
					this.SendPropertyChanging();
					this._CauC = value;
					this.SendPropertyChanged("CauC");
					this.OnCauCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CauD", DbType="NVarChar(1000)")]
		public string CauD
		{
			get
			{
				return this._CauD;
			}
			set
			{
				if ((this._CauD != value))
				{
					this.OnCauDChanging(value);
					this.SendPropertyChanging();
					this._CauD = value;
					this.SendPropertyChanged("CauD");
					this.OnCauDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoiY", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string GoiY
		{
			get
			{
				return this._GoiY;
			}
			set
			{
				if ((this._GoiY != value))
				{
					this.OnGoiYChanging(value);
					this.SendPropertyChanging();
					this._GoiY = value;
					this.SendPropertyChanged("GoiY");
					this.OnGoiYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DapAn", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string DapAn
		{
			get
			{
				return this._DapAn;
			}
			set
			{
				if ((this._DapAn != value))
				{
					this.OnDapAnChanging(value);
					this.SendPropertyChanging();
					this._DapAn = value;
					this.SendPropertyChanged("DapAn");
					this.OnDapAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CAUHOI_CHITIETDETHI", Storage="_CHITIETDETHIs", ThisKey="MaCauHoi", OtherKey="MaCauHoi")]
		public EntitySet<CHITIETDETHI> CHITIETDETHIs
		{
			get
			{
				return this._CHITIETDETHIs;
			}
			set
			{
				this._CHITIETDETHIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CAPDOCAUHOI_CAUHOI", Storage="_CAPDOCAUHOI", ThisKey="MaCapDo", OtherKey="MaCapDo", IsForeignKey=true)]
		public CAPDOCAUHOI CAPDOCAUHOI
		{
			get
			{
				return this._CAPDOCAUHOI.Entity;
			}
			set
			{
				CAPDOCAUHOI previousValue = this._CAPDOCAUHOI.Entity;
				if (((previousValue != value) 
							|| (this._CAPDOCAUHOI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CAPDOCAUHOI.Entity = null;
						previousValue.CAUHOIs.Remove(this);
					}
					this._CAPDOCAUHOI.Entity = value;
					if ((value != null))
					{
						value.CAUHOIs.Add(this);
						this._MaCapDo = value.MaCapDo;
					}
					else
					{
						this._MaCapDo = default(string);
					}
					this.SendPropertyChanged("CAPDOCAUHOI");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHOI_CAUHOI", Storage="_KHOI", ThisKey="MaKhoi", OtherKey="MaKhoi", IsForeignKey=true)]
		public KHOI KHOI
		{
			get
			{
				return this._KHOI.Entity;
			}
			set
			{
				KHOI previousValue = this._KHOI.Entity;
				if (((previousValue != value) 
							|| (this._KHOI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHOI.Entity = null;
						previousValue.CAUHOIs.Remove(this);
					}
					this._KHOI.Entity = value;
					if ((value != null))
					{
						value.CAUHOIs.Add(this);
						this._MaKhoi = value.MaKhoi;
					}
					else
					{
						this._MaKhoi = default(string);
					}
					this.SendPropertyChanged("KHOI");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAICAUHOI_CAUHOI", Storage="_LOAICAUHOI", ThisKey="MaLoaiCauHoi", OtherKey="MaLoaiCauHoi", IsForeignKey=true)]
		public LOAICAUHOI LOAICAUHOI
		{
			get
			{
				return this._LOAICAUHOI.Entity;
			}
			set
			{
				LOAICAUHOI previousValue = this._LOAICAUHOI.Entity;
				if (((previousValue != value) 
							|| (this._LOAICAUHOI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAICAUHOI.Entity = null;
						previousValue.CAUHOIs.Remove(this);
					}
					this._LOAICAUHOI.Entity = value;
					if ((value != null))
					{
						value.CAUHOIs.Add(this);
						this._MaLoaiCauHoi = value.MaLoaiCauHoi;
					}
					else
					{
						this._MaLoaiCauHoi = default(string);
					}
					this.SendPropertyChanged("LOAICAUHOI");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MONHOC_CAUHOI", Storage="_MONHOC", ThisKey="MaMonHoc", OtherKey="MaMonHoc", IsForeignKey=true)]
		public MONHOC MONHOC
		{
			get
			{
				return this._MONHOC.Entity;
			}
			set
			{
				MONHOC previousValue = this._MONHOC.Entity;
				if (((previousValue != value) 
							|| (this._MONHOC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MONHOC.Entity = null;
						previousValue.CAUHOIs.Remove(this);
					}
					this._MONHOC.Entity = value;
					if ((value != null))
					{
						value.CAUHOIs.Add(this);
						this._MaMonHoc = value.MaMonHoc;
					}
					else
					{
						this._MaMonHoc = default(string);
					}
					this.SendPropertyChanged("MONHOC");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETDETHIs(CHITIETDETHI entity)
		{
			this.SendPropertyChanging();
			entity.CAUHOI = this;
		}
		
		private void detach_CHITIETDETHIs(CHITIETDETHI entity)
		{
			this.SendPropertyChanging();
			entity.CAUHOI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETDETHI")]
	public partial class CHITIETDETHI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDeThi;
		
		private string _MaCauHoi;
		
		private EntityRef<CAUHOI> _CAUHOI;
		
		private EntityRef<DETHI> _DETHI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDeThiChanging(string value);
    partial void OnMaDeThiChanged();
    partial void OnMaCauHoiChanging(string value);
    partial void OnMaCauHoiChanged();
    #endregion
		
		public CHITIETDETHI()
		{
			this._CAUHOI = default(EntityRef<CAUHOI>);
			this._DETHI = default(EntityRef<DETHI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDeThi", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDeThi
		{
			get
			{
				return this._MaDeThi;
			}
			set
			{
				if ((this._MaDeThi != value))
				{
					if (this._DETHI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDeThiChanging(value);
					this.SendPropertyChanging();
					this._MaDeThi = value;
					this.SendPropertyChanged("MaDeThi");
					this.OnMaDeThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCauHoi", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaCauHoi
		{
			get
			{
				return this._MaCauHoi;
			}
			set
			{
				if ((this._MaCauHoi != value))
				{
					if (this._CAUHOI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaCauHoiChanging(value);
					this.SendPropertyChanging();
					this._MaCauHoi = value;
					this.SendPropertyChanged("MaCauHoi");
					this.OnMaCauHoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CAUHOI_CHITIETDETHI", Storage="_CAUHOI", ThisKey="MaCauHoi", OtherKey="MaCauHoi", IsForeignKey=true)]
		public CAUHOI CAUHOI
		{
			get
			{
				return this._CAUHOI.Entity;
			}
			set
			{
				CAUHOI previousValue = this._CAUHOI.Entity;
				if (((previousValue != value) 
							|| (this._CAUHOI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CAUHOI.Entity = null;
						previousValue.CHITIETDETHIs.Remove(this);
					}
					this._CAUHOI.Entity = value;
					if ((value != null))
					{
						value.CHITIETDETHIs.Add(this);
						this._MaCauHoi = value.MaCauHoi;
					}
					else
					{
						this._MaCauHoi = default(string);
					}
					this.SendPropertyChanged("CAUHOI");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DETHI_CHITIETDETHI", Storage="_DETHI", ThisKey="MaDeThi", OtherKey="MaDeThi", IsForeignKey=true)]
		public DETHI DETHI
		{
			get
			{
				return this._DETHI.Entity;
			}
			set
			{
				DETHI previousValue = this._DETHI.Entity;
				if (((previousValue != value) 
							|| (this._DETHI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DETHI.Entity = null;
						previousValue.CHITIETDETHIs.Remove(this);
					}
					this._DETHI.Entity = value;
					if ((value != null))
					{
						value.CHITIETDETHIs.Add(this);
						this._MaDeThi = value.MaDeThi;
					}
					else
					{
						this._MaDeThi = default(string);
					}
					this.SendPropertyChanged("DETHI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETKYTHI")]
	public partial class CHITIETKYTHI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKyThi;
		
		private string _MaDeThi;
		
		private System.Nullable<System.DateTime> _ThoiGianBatDau;
		
		private System.Nullable<System.DateTime> _ThoiGianKetThuc;
		
		private EntitySet<KETQUATHI> _KETQUATHIs;
		
		private EntityRef<DETHI> _DETHI;
		
		private EntityRef<KYTHI> _KYTHI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKyThiChanging(string value);
    partial void OnMaKyThiChanged();
    partial void OnMaDeThiChanging(string value);
    partial void OnMaDeThiChanged();
    partial void OnThoiGianBatDauChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianBatDauChanged();
    partial void OnThoiGianKetThucChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianKetThucChanged();
    #endregion
		
		public CHITIETKYTHI()
		{
			this._KETQUATHIs = new EntitySet<KETQUATHI>(new Action<KETQUATHI>(this.attach_KETQUATHIs), new Action<KETQUATHI>(this.detach_KETQUATHIs));
			this._DETHI = default(EntityRef<DETHI>);
			this._KYTHI = default(EntityRef<KYTHI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKyThi", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKyThi
		{
			get
			{
				return this._MaKyThi;
			}
			set
			{
				if ((this._MaKyThi != value))
				{
					if (this._KYTHI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKyThiChanging(value);
					this.SendPropertyChanging();
					this._MaKyThi = value;
					this.SendPropertyChanged("MaKyThi");
					this.OnMaKyThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDeThi", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDeThi
		{
			get
			{
				return this._MaDeThi;
			}
			set
			{
				if ((this._MaDeThi != value))
				{
					if (this._DETHI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDeThiChanging(value);
					this.SendPropertyChanging();
					this._MaDeThi = value;
					this.SendPropertyChanged("MaDeThi");
					this.OnMaDeThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianBatDau", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianBatDau
		{
			get
			{
				return this._ThoiGianBatDau;
			}
			set
			{
				if ((this._ThoiGianBatDau != value))
				{
					this.OnThoiGianBatDauChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianBatDau = value;
					this.SendPropertyChanged("ThoiGianBatDau");
					this.OnThoiGianBatDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianKetThuc", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianKetThuc
		{
			get
			{
				return this._ThoiGianKetThuc;
			}
			set
			{
				if ((this._ThoiGianKetThuc != value))
				{
					this.OnThoiGianKetThucChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianKetThuc = value;
					this.SendPropertyChanged("ThoiGianKetThuc");
					this.OnThoiGianKetThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHITIETKYTHI_KETQUATHI", Storage="_KETQUATHIs", ThisKey="MaKyThi,MaDeThi", OtherKey="MaKyThi,MaDeThi")]
		public EntitySet<KETQUATHI> KETQUATHIs
		{
			get
			{
				return this._KETQUATHIs;
			}
			set
			{
				this._KETQUATHIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DETHI_CHITIETKYTHI", Storage="_DETHI", ThisKey="MaDeThi", OtherKey="MaDeThi", IsForeignKey=true)]
		public DETHI DETHI
		{
			get
			{
				return this._DETHI.Entity;
			}
			set
			{
				DETHI previousValue = this._DETHI.Entity;
				if (((previousValue != value) 
							|| (this._DETHI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DETHI.Entity = null;
						previousValue.CHITIETKYTHIs.Remove(this);
					}
					this._DETHI.Entity = value;
					if ((value != null))
					{
						value.CHITIETKYTHIs.Add(this);
						this._MaDeThi = value.MaDeThi;
					}
					else
					{
						this._MaDeThi = default(string);
					}
					this.SendPropertyChanged("DETHI");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KYTHI_CHITIETKYTHI", Storage="_KYTHI", ThisKey="MaKyThi", OtherKey="MaKyThi", IsForeignKey=true)]
		public KYTHI KYTHI
		{
			get
			{
				return this._KYTHI.Entity;
			}
			set
			{
				KYTHI previousValue = this._KYTHI.Entity;
				if (((previousValue != value) 
							|| (this._KYTHI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KYTHI.Entity = null;
						previousValue.CHITIETKYTHIs.Remove(this);
					}
					this._KYTHI.Entity = value;
					if ((value != null))
					{
						value.CHITIETKYTHIs.Add(this);
						this._MaKyThi = value.MaKyThi;
					}
					else
					{
						this._MaKyThi = default(string);
					}
					this.SendPropertyChanged("KYTHI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KETQUATHIs(KETQUATHI entity)
		{
			this.SendPropertyChanging();
			entity.CHITIETKYTHI = this;
		}
		
		private void detach_KETQUATHIs(KETQUATHI entity)
		{
			this.SendPropertyChanging();
			entity.CHITIETKYTHI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DANHSACHTHISINH")]
	public partial class DANHSACHTHISINH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKyThi;
		
		private string _TaiKhoan;
		
		private EntityRef<KYTHI> _KYTHI;
		
		private EntityRef<NGUOIDUNG> _NGUOIDUNG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKyThiChanging(string value);
    partial void OnMaKyThiChanged();
    partial void OnTaiKhoanChanging(string value);
    partial void OnTaiKhoanChanged();
    #endregion
		
		public DANHSACHTHISINH()
		{
			this._KYTHI = default(EntityRef<KYTHI>);
			this._NGUOIDUNG = default(EntityRef<NGUOIDUNG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKyThi", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKyThi
		{
			get
			{
				return this._MaKyThi;
			}
			set
			{
				if ((this._MaKyThi != value))
				{
					if (this._KYTHI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKyThiChanging(value);
					this.SendPropertyChanging();
					this._MaKyThi = value;
					this.SendPropertyChanged("MaKyThi");
					this.OnMaKyThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoan", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TaiKhoan
		{
			get
			{
				return this._TaiKhoan;
			}
			set
			{
				if ((this._TaiKhoan != value))
				{
					if (this._NGUOIDUNG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoan = value;
					this.SendPropertyChanged("TaiKhoan");
					this.OnTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KYTHI_DANHSACHTHISINH", Storage="_KYTHI", ThisKey="MaKyThi", OtherKey="MaKyThi", IsForeignKey=true)]
		public KYTHI KYTHI
		{
			get
			{
				return this._KYTHI.Entity;
			}
			set
			{
				KYTHI previousValue = this._KYTHI.Entity;
				if (((previousValue != value) 
							|| (this._KYTHI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KYTHI.Entity = null;
						previousValue.DANHSACHTHISINHs.Remove(this);
					}
					this._KYTHI.Entity = value;
					if ((value != null))
					{
						value.DANHSACHTHISINHs.Add(this);
						this._MaKyThi = value.MaKyThi;
					}
					else
					{
						this._MaKyThi = default(string);
					}
					this.SendPropertyChanged("KYTHI");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NGUOIDUNG_DANHSACHTHISINH", Storage="_NGUOIDUNG", ThisKey="TaiKhoan", OtherKey="TaiKhoan", IsForeignKey=true)]
		public NGUOIDUNG NGUOIDUNG
		{
			get
			{
				return this._NGUOIDUNG.Entity;
			}
			set
			{
				NGUOIDUNG previousValue = this._NGUOIDUNG.Entity;
				if (((previousValue != value) 
							|| (this._NGUOIDUNG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NGUOIDUNG.Entity = null;
						previousValue.DANHSACHTHISINHs.Remove(this);
					}
					this._NGUOIDUNG.Entity = value;
					if ((value != null))
					{
						value.DANHSACHTHISINHs.Add(this);
						this._TaiKhoan = value.TaiKhoan;
					}
					else
					{
						this._TaiKhoan = default(string);
					}
					this.SendPropertyChanged("NGUOIDUNG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DETHI")]
	public partial class DETHI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDeThi;
		
		private string _MaMonHoc;
		
		private string _MaKhoi;
		
		private System.Nullable<int> _ThoiGianLamBai;
		
		private EntitySet<CHITIETDETHI> _CHITIETDETHIs;
		
		private EntitySet<CHITIETKYTHI> _CHITIETKYTHIs;
		
		private EntityRef<KHOI> _KHOI;
		
		private EntityRef<MONHOC> _MONHOC;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDeThiChanging(string value);
    partial void OnMaDeThiChanged();
    partial void OnMaMonHocChanging(string value);
    partial void OnMaMonHocChanged();
    partial void OnMaKhoiChanging(string value);
    partial void OnMaKhoiChanged();
    partial void OnThoiGianLamBaiChanging(System.Nullable<int> value);
    partial void OnThoiGianLamBaiChanged();
    #endregion
		
		public DETHI()
		{
			this._CHITIETDETHIs = new EntitySet<CHITIETDETHI>(new Action<CHITIETDETHI>(this.attach_CHITIETDETHIs), new Action<CHITIETDETHI>(this.detach_CHITIETDETHIs));
			this._CHITIETKYTHIs = new EntitySet<CHITIETKYTHI>(new Action<CHITIETKYTHI>(this.attach_CHITIETKYTHIs), new Action<CHITIETKYTHI>(this.detach_CHITIETKYTHIs));
			this._KHOI = default(EntityRef<KHOI>);
			this._MONHOC = default(EntityRef<MONHOC>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDeThi", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDeThi
		{
			get
			{
				return this._MaDeThi;
			}
			set
			{
				if ((this._MaDeThi != value))
				{
					this.OnMaDeThiChanging(value);
					this.SendPropertyChanging();
					this._MaDeThi = value;
					this.SendPropertyChanged("MaDeThi");
					this.OnMaDeThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMonHoc", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MaMonHoc
		{
			get
			{
				return this._MaMonHoc;
			}
			set
			{
				if ((this._MaMonHoc != value))
				{
					if (this._MONHOC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaMonHocChanging(value);
					this.SendPropertyChanging();
					this._MaMonHoc = value;
					this.SendPropertyChanged("MaMonHoc");
					this.OnMaMonHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhoi", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MaKhoi
		{
			get
			{
				return this._MaKhoi;
			}
			set
			{
				if ((this._MaKhoi != value))
				{
					if (this._KHOI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhoiChanging(value);
					this.SendPropertyChanging();
					this._MaKhoi = value;
					this.SendPropertyChanged("MaKhoi");
					this.OnMaKhoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianLamBai", DbType="Int")]
		public System.Nullable<int> ThoiGianLamBai
		{
			get
			{
				return this._ThoiGianLamBai;
			}
			set
			{
				if ((this._ThoiGianLamBai != value))
				{
					this.OnThoiGianLamBaiChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianLamBai = value;
					this.SendPropertyChanged("ThoiGianLamBai");
					this.OnThoiGianLamBaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DETHI_CHITIETDETHI", Storage="_CHITIETDETHIs", ThisKey="MaDeThi", OtherKey="MaDeThi")]
		public EntitySet<CHITIETDETHI> CHITIETDETHIs
		{
			get
			{
				return this._CHITIETDETHIs;
			}
			set
			{
				this._CHITIETDETHIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DETHI_CHITIETKYTHI", Storage="_CHITIETKYTHIs", ThisKey="MaDeThi", OtherKey="MaDeThi")]
		public EntitySet<CHITIETKYTHI> CHITIETKYTHIs
		{
			get
			{
				return this._CHITIETKYTHIs;
			}
			set
			{
				this._CHITIETKYTHIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHOI_DETHI", Storage="_KHOI", ThisKey="MaKhoi", OtherKey="MaKhoi", IsForeignKey=true)]
		public KHOI KHOI
		{
			get
			{
				return this._KHOI.Entity;
			}
			set
			{
				KHOI previousValue = this._KHOI.Entity;
				if (((previousValue != value) 
							|| (this._KHOI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHOI.Entity = null;
						previousValue.DETHIs.Remove(this);
					}
					this._KHOI.Entity = value;
					if ((value != null))
					{
						value.DETHIs.Add(this);
						this._MaKhoi = value.MaKhoi;
					}
					else
					{
						this._MaKhoi = default(string);
					}
					this.SendPropertyChanged("KHOI");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MONHOC_DETHI", Storage="_MONHOC", ThisKey="MaMonHoc", OtherKey="MaMonHoc", IsForeignKey=true)]
		public MONHOC MONHOC
		{
			get
			{
				return this._MONHOC.Entity;
			}
			set
			{
				MONHOC previousValue = this._MONHOC.Entity;
				if (((previousValue != value) 
							|| (this._MONHOC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MONHOC.Entity = null;
						previousValue.DETHIs.Remove(this);
					}
					this._MONHOC.Entity = value;
					if ((value != null))
					{
						value.DETHIs.Add(this);
						this._MaMonHoc = value.MaMonHoc;
					}
					else
					{
						this._MaMonHoc = default(string);
					}
					this.SendPropertyChanged("MONHOC");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETDETHIs(CHITIETDETHI entity)
		{
			this.SendPropertyChanging();
			entity.DETHI = this;
		}
		
		private void detach_CHITIETDETHIs(CHITIETDETHI entity)
		{
			this.SendPropertyChanging();
			entity.DETHI = null;
		}
		
		private void attach_CHITIETKYTHIs(CHITIETKYTHI entity)
		{
			this.SendPropertyChanging();
			entity.DETHI = this;
		}
		
		private void detach_CHITIETKYTHIs(CHITIETKYTHI entity)
		{
			this.SendPropertyChanging();
			entity.DETHI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KETQUATHI")]
	public partial class KETQUATHI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKyThi;
		
		private string _MaDeThi;
		
		private string _TaiKhoan;
		
		private System.Nullable<System.DateTime> _ThoiGianBatDau;
		
		private System.Nullable<System.DateTime> _ThoiGianKetThuc;
		
		private System.Nullable<double> _Diem;
		
		private EntityRef<CHITIETKYTHI> _CHITIETKYTHI;
		
		private EntityRef<NGUOIDUNG> _NGUOIDUNG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKyThiChanging(string value);
    partial void OnMaKyThiChanged();
    partial void OnMaDeThiChanging(string value);
    partial void OnMaDeThiChanged();
    partial void OnTaiKhoanChanging(string value);
    partial void OnTaiKhoanChanged();
    partial void OnThoiGianBatDauChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianBatDauChanged();
    partial void OnThoiGianKetThucChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianKetThucChanged();
    partial void OnDiemChanging(System.Nullable<double> value);
    partial void OnDiemChanged();
    #endregion
		
		public KETQUATHI()
		{
			this._CHITIETKYTHI = default(EntityRef<CHITIETKYTHI>);
			this._NGUOIDUNG = default(EntityRef<NGUOIDUNG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKyThi", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKyThi
		{
			get
			{
				return this._MaKyThi;
			}
			set
			{
				if ((this._MaKyThi != value))
				{
					if (this._CHITIETKYTHI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKyThiChanging(value);
					this.SendPropertyChanging();
					this._MaKyThi = value;
					this.SendPropertyChanged("MaKyThi");
					this.OnMaKyThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDeThi", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDeThi
		{
			get
			{
				return this._MaDeThi;
			}
			set
			{
				if ((this._MaDeThi != value))
				{
					if (this._CHITIETKYTHI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDeThiChanging(value);
					this.SendPropertyChanging();
					this._MaDeThi = value;
					this.SendPropertyChanged("MaDeThi");
					this.OnMaDeThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoan", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TaiKhoan
		{
			get
			{
				return this._TaiKhoan;
			}
			set
			{
				if ((this._TaiKhoan != value))
				{
					if (this._NGUOIDUNG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoan = value;
					this.SendPropertyChanged("TaiKhoan");
					this.OnTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianBatDau", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianBatDau
		{
			get
			{
				return this._ThoiGianBatDau;
			}
			set
			{
				if ((this._ThoiGianBatDau != value))
				{
					this.OnThoiGianBatDauChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianBatDau = value;
					this.SendPropertyChanged("ThoiGianBatDau");
					this.OnThoiGianBatDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianKetThuc", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianKetThuc
		{
			get
			{
				return this._ThoiGianKetThuc;
			}
			set
			{
				if ((this._ThoiGianKetThuc != value))
				{
					this.OnThoiGianKetThucChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianKetThuc = value;
					this.SendPropertyChanged("ThoiGianKetThuc");
					this.OnThoiGianKetThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diem", DbType="Float")]
		public System.Nullable<double> Diem
		{
			get
			{
				return this._Diem;
			}
			set
			{
				if ((this._Diem != value))
				{
					this.OnDiemChanging(value);
					this.SendPropertyChanging();
					this._Diem = value;
					this.SendPropertyChanged("Diem");
					this.OnDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHITIETKYTHI_KETQUATHI", Storage="_CHITIETKYTHI", ThisKey="MaKyThi,MaDeThi", OtherKey="MaKyThi,MaDeThi", IsForeignKey=true)]
		public CHITIETKYTHI CHITIETKYTHI
		{
			get
			{
				return this._CHITIETKYTHI.Entity;
			}
			set
			{
				CHITIETKYTHI previousValue = this._CHITIETKYTHI.Entity;
				if (((previousValue != value) 
							|| (this._CHITIETKYTHI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CHITIETKYTHI.Entity = null;
						previousValue.KETQUATHIs.Remove(this);
					}
					this._CHITIETKYTHI.Entity = value;
					if ((value != null))
					{
						value.KETQUATHIs.Add(this);
						this._MaKyThi = value.MaKyThi;
						this._MaDeThi = value.MaDeThi;
					}
					else
					{
						this._MaKyThi = default(string);
						this._MaDeThi = default(string);
					}
					this.SendPropertyChanged("CHITIETKYTHI");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NGUOIDUNG_KETQUATHI", Storage="_NGUOIDUNG", ThisKey="TaiKhoan", OtherKey="TaiKhoan", IsForeignKey=true)]
		public NGUOIDUNG NGUOIDUNG
		{
			get
			{
				return this._NGUOIDUNG.Entity;
			}
			set
			{
				NGUOIDUNG previousValue = this._NGUOIDUNG.Entity;
				if (((previousValue != value) 
							|| (this._NGUOIDUNG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NGUOIDUNG.Entity = null;
						previousValue.KETQUATHIs.Remove(this);
					}
					this._NGUOIDUNG.Entity = value;
					if ((value != null))
					{
						value.KETQUATHIs.Add(this);
						this._TaiKhoan = value.TaiKhoan;
					}
					else
					{
						this._TaiKhoan = default(string);
					}
					this.SendPropertyChanged("NGUOIDUNG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHOI")]
	public partial class KHOI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKhoi;
		
		private string _TenKhoi;
		
		private EntitySet<CAUHOI> _CAUHOIs;
		
		private EntitySet<DETHI> _DETHIs;
		
		private EntitySet<LOPHOC> _LOPHOCs;
		
		private EntitySet<NGUOIDUNG> _NGUOIDUNGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhoiChanging(string value);
    partial void OnMaKhoiChanged();
    partial void OnTenKhoiChanging(string value);
    partial void OnTenKhoiChanged();
    #endregion
		
		public KHOI()
		{
			this._CAUHOIs = new EntitySet<CAUHOI>(new Action<CAUHOI>(this.attach_CAUHOIs), new Action<CAUHOI>(this.detach_CAUHOIs));
			this._DETHIs = new EntitySet<DETHI>(new Action<DETHI>(this.attach_DETHIs), new Action<DETHI>(this.detach_DETHIs));
			this._LOPHOCs = new EntitySet<LOPHOC>(new Action<LOPHOC>(this.attach_LOPHOCs), new Action<LOPHOC>(this.detach_LOPHOCs));
			this._NGUOIDUNGs = new EntitySet<NGUOIDUNG>(new Action<NGUOIDUNG>(this.attach_NGUOIDUNGs), new Action<NGUOIDUNG>(this.detach_NGUOIDUNGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhoi", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKhoi
		{
			get
			{
				return this._MaKhoi;
			}
			set
			{
				if ((this._MaKhoi != value))
				{
					this.OnMaKhoiChanging(value);
					this.SendPropertyChanging();
					this._MaKhoi = value;
					this.SendPropertyChanged("MaKhoi");
					this.OnMaKhoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhoi", DbType="NVarChar(50)")]
		public string TenKhoi
		{
			get
			{
				return this._TenKhoi;
			}
			set
			{
				if ((this._TenKhoi != value))
				{
					this.OnTenKhoiChanging(value);
					this.SendPropertyChanging();
					this._TenKhoi = value;
					this.SendPropertyChanged("TenKhoi");
					this.OnTenKhoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHOI_CAUHOI", Storage="_CAUHOIs", ThisKey="MaKhoi", OtherKey="MaKhoi")]
		public EntitySet<CAUHOI> CAUHOIs
		{
			get
			{
				return this._CAUHOIs;
			}
			set
			{
				this._CAUHOIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHOI_DETHI", Storage="_DETHIs", ThisKey="MaKhoi", OtherKey="MaKhoi")]
		public EntitySet<DETHI> DETHIs
		{
			get
			{
				return this._DETHIs;
			}
			set
			{
				this._DETHIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHOI_LOPHOC", Storage="_LOPHOCs", ThisKey="MaKhoi", OtherKey="MaKhoi")]
		public EntitySet<LOPHOC> LOPHOCs
		{
			get
			{
				return this._LOPHOCs;
			}
			set
			{
				this._LOPHOCs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHOI_NGUOIDUNG", Storage="_NGUOIDUNGs", ThisKey="MaKhoi", OtherKey="MaKhoi")]
		public EntitySet<NGUOIDUNG> NGUOIDUNGs
		{
			get
			{
				return this._NGUOIDUNGs;
			}
			set
			{
				this._NGUOIDUNGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CAUHOIs(CAUHOI entity)
		{
			this.SendPropertyChanging();
			entity.KHOI = this;
		}
		
		private void detach_CAUHOIs(CAUHOI entity)
		{
			this.SendPropertyChanging();
			entity.KHOI = null;
		}
		
		private void attach_DETHIs(DETHI entity)
		{
			this.SendPropertyChanging();
			entity.KHOI = this;
		}
		
		private void detach_DETHIs(DETHI entity)
		{
			this.SendPropertyChanging();
			entity.KHOI = null;
		}
		
		private void attach_LOPHOCs(LOPHOC entity)
		{
			this.SendPropertyChanging();
			entity.KHOI = this;
		}
		
		private void detach_LOPHOCs(LOPHOC entity)
		{
			this.SendPropertyChanging();
			entity.KHOI = null;
		}
		
		private void attach_NGUOIDUNGs(NGUOIDUNG entity)
		{
			this.SendPropertyChanging();
			entity.KHOI = this;
		}
		
		private void detach_NGUOIDUNGs(NGUOIDUNG entity)
		{
			this.SendPropertyChanging();
			entity.KHOI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KYTHI")]
	public partial class KYTHI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKyThi;
		
		private string _TenKyThi;
		
		private string _MaLoaiKyThi;
		
		private System.Nullable<System.DateTime> _ThoiGianBatDau;
		
		private System.Nullable<System.DateTime> _ThoiGianKetThuc;
		
		private EntitySet<CHITIETKYTHI> _CHITIETKYTHIs;
		
		private EntitySet<DANHSACHTHISINH> _DANHSACHTHISINHs;
		
		private EntityRef<LOAIKYTHI> _LOAIKYTHI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKyThiChanging(string value);
    partial void OnMaKyThiChanged();
    partial void OnTenKyThiChanging(string value);
    partial void OnTenKyThiChanged();
    partial void OnMaLoaiKyThiChanging(string value);
    partial void OnMaLoaiKyThiChanged();
    partial void OnThoiGianBatDauChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianBatDauChanged();
    partial void OnThoiGianKetThucChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianKetThucChanged();
    #endregion
		
		public KYTHI()
		{
			this._CHITIETKYTHIs = new EntitySet<CHITIETKYTHI>(new Action<CHITIETKYTHI>(this.attach_CHITIETKYTHIs), new Action<CHITIETKYTHI>(this.detach_CHITIETKYTHIs));
			this._DANHSACHTHISINHs = new EntitySet<DANHSACHTHISINH>(new Action<DANHSACHTHISINH>(this.attach_DANHSACHTHISINHs), new Action<DANHSACHTHISINH>(this.detach_DANHSACHTHISINHs));
			this._LOAIKYTHI = default(EntityRef<LOAIKYTHI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKyThi", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKyThi
		{
			get
			{
				return this._MaKyThi;
			}
			set
			{
				if ((this._MaKyThi != value))
				{
					this.OnMaKyThiChanging(value);
					this.SendPropertyChanging();
					this._MaKyThi = value;
					this.SendPropertyChanged("MaKyThi");
					this.OnMaKyThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKyThi", DbType="NVarChar(50)")]
		public string TenKyThi
		{
			get
			{
				return this._TenKyThi;
			}
			set
			{
				if ((this._TenKyThi != value))
				{
					this.OnTenKyThiChanging(value);
					this.SendPropertyChanging();
					this._TenKyThi = value;
					this.SendPropertyChanged("TenKyThi");
					this.OnTenKyThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiKyThi", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MaLoaiKyThi
		{
			get
			{
				return this._MaLoaiKyThi;
			}
			set
			{
				if ((this._MaLoaiKyThi != value))
				{
					if (this._LOAIKYTHI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiKyThiChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiKyThi = value;
					this.SendPropertyChanged("MaLoaiKyThi");
					this.OnMaLoaiKyThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianBatDau", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianBatDau
		{
			get
			{
				return this._ThoiGianBatDau;
			}
			set
			{
				if ((this._ThoiGianBatDau != value))
				{
					this.OnThoiGianBatDauChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianBatDau = value;
					this.SendPropertyChanged("ThoiGianBatDau");
					this.OnThoiGianBatDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianKetThuc", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianKetThuc
		{
			get
			{
				return this._ThoiGianKetThuc;
			}
			set
			{
				if ((this._ThoiGianKetThuc != value))
				{
					this.OnThoiGianKetThucChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianKetThuc = value;
					this.SendPropertyChanged("ThoiGianKetThuc");
					this.OnThoiGianKetThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KYTHI_CHITIETKYTHI", Storage="_CHITIETKYTHIs", ThisKey="MaKyThi", OtherKey="MaKyThi")]
		public EntitySet<CHITIETKYTHI> CHITIETKYTHIs
		{
			get
			{
				return this._CHITIETKYTHIs;
			}
			set
			{
				this._CHITIETKYTHIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KYTHI_DANHSACHTHISINH", Storage="_DANHSACHTHISINHs", ThisKey="MaKyThi", OtherKey="MaKyThi")]
		public EntitySet<DANHSACHTHISINH> DANHSACHTHISINHs
		{
			get
			{
				return this._DANHSACHTHISINHs;
			}
			set
			{
				this._DANHSACHTHISINHs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIKYTHI_KYTHI", Storage="_LOAIKYTHI", ThisKey="MaLoaiKyThi", OtherKey="MaLoaiKyThi", IsForeignKey=true)]
		public LOAIKYTHI LOAIKYTHI
		{
			get
			{
				return this._LOAIKYTHI.Entity;
			}
			set
			{
				LOAIKYTHI previousValue = this._LOAIKYTHI.Entity;
				if (((previousValue != value) 
							|| (this._LOAIKYTHI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAIKYTHI.Entity = null;
						previousValue.KYTHIs.Remove(this);
					}
					this._LOAIKYTHI.Entity = value;
					if ((value != null))
					{
						value.KYTHIs.Add(this);
						this._MaLoaiKyThi = value.MaLoaiKyThi;
					}
					else
					{
						this._MaLoaiKyThi = default(string);
					}
					this.SendPropertyChanged("LOAIKYTHI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETKYTHIs(CHITIETKYTHI entity)
		{
			this.SendPropertyChanging();
			entity.KYTHI = this;
		}
		
		private void detach_CHITIETKYTHIs(CHITIETKYTHI entity)
		{
			this.SendPropertyChanging();
			entity.KYTHI = null;
		}
		
		private void attach_DANHSACHTHISINHs(DANHSACHTHISINH entity)
		{
			this.SendPropertyChanging();
			entity.KYTHI = this;
		}
		
		private void detach_DANHSACHTHISINHs(DANHSACHTHISINH entity)
		{
			this.SendPropertyChanging();
			entity.KYTHI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAICAUHOI")]
	public partial class LOAICAUHOI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLoaiCauHoi;
		
		private string _TenLoaiCauHoi;
		
		private EntitySet<CAUHOI> _CAUHOIs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiCauHoiChanging(string value);
    partial void OnMaLoaiCauHoiChanged();
    partial void OnTenLoaiCauHoiChanging(string value);
    partial void OnTenLoaiCauHoiChanged();
    #endregion
		
		public LOAICAUHOI()
		{
			this._CAUHOIs = new EntitySet<CAUHOI>(new Action<CAUHOI>(this.attach_CAUHOIs), new Action<CAUHOI>(this.detach_CAUHOIs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiCauHoi", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLoaiCauHoi
		{
			get
			{
				return this._MaLoaiCauHoi;
			}
			set
			{
				if ((this._MaLoaiCauHoi != value))
				{
					this.OnMaLoaiCauHoiChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiCauHoi = value;
					this.SendPropertyChanged("MaLoaiCauHoi");
					this.OnMaLoaiCauHoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiCauHoi", DbType="NVarChar(50)")]
		public string TenLoaiCauHoi
		{
			get
			{
				return this._TenLoaiCauHoi;
			}
			set
			{
				if ((this._TenLoaiCauHoi != value))
				{
					this.OnTenLoaiCauHoiChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiCauHoi = value;
					this.SendPropertyChanged("TenLoaiCauHoi");
					this.OnTenLoaiCauHoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAICAUHOI_CAUHOI", Storage="_CAUHOIs", ThisKey="MaLoaiCauHoi", OtherKey="MaLoaiCauHoi")]
		public EntitySet<CAUHOI> CAUHOIs
		{
			get
			{
				return this._CAUHOIs;
			}
			set
			{
				this._CAUHOIs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CAUHOIs(CAUHOI entity)
		{
			this.SendPropertyChanging();
			entity.LOAICAUHOI = this;
		}
		
		private void detach_CAUHOIs(CAUHOI entity)
		{
			this.SendPropertyChanging();
			entity.LOAICAUHOI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAIKYTHI")]
	public partial class LOAIKYTHI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLoaiKyThi;
		
		private string _TenLoaiKyThi;
		
		private EntitySet<KYTHI> _KYTHIs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiKyThiChanging(string value);
    partial void OnMaLoaiKyThiChanged();
    partial void OnTenLoaiKyThiChanging(string value);
    partial void OnTenLoaiKyThiChanged();
    #endregion
		
		public LOAIKYTHI()
		{
			this._KYTHIs = new EntitySet<KYTHI>(new Action<KYTHI>(this.attach_KYTHIs), new Action<KYTHI>(this.detach_KYTHIs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiKyThi", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLoaiKyThi
		{
			get
			{
				return this._MaLoaiKyThi;
			}
			set
			{
				if ((this._MaLoaiKyThi != value))
				{
					this.OnMaLoaiKyThiChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiKyThi = value;
					this.SendPropertyChanged("MaLoaiKyThi");
					this.OnMaLoaiKyThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiKyThi", DbType="NVarChar(50)")]
		public string TenLoaiKyThi
		{
			get
			{
				return this._TenLoaiKyThi;
			}
			set
			{
				if ((this._TenLoaiKyThi != value))
				{
					this.OnTenLoaiKyThiChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiKyThi = value;
					this.SendPropertyChanged("TenLoaiKyThi");
					this.OnTenLoaiKyThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIKYTHI_KYTHI", Storage="_KYTHIs", ThisKey="MaLoaiKyThi", OtherKey="MaLoaiKyThi")]
		public EntitySet<KYTHI> KYTHIs
		{
			get
			{
				return this._KYTHIs;
			}
			set
			{
				this._KYTHIs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KYTHIs(KYTHI entity)
		{
			this.SendPropertyChanging();
			entity.LOAIKYTHI = this;
		}
		
		private void detach_KYTHIs(KYTHI entity)
		{
			this.SendPropertyChanging();
			entity.LOAIKYTHI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOPHOC")]
	public partial class LOPHOC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLop;
		
		private string _TenLop;
		
		private string _MaKhoi;
		
		private EntitySet<NGUOIDUNG> _NGUOIDUNGs;
		
		private EntityRef<KHOI> _KHOI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLopChanging(string value);
    partial void OnMaLopChanged();
    partial void OnTenLopChanging(string value);
    partial void OnTenLopChanged();
    partial void OnMaKhoiChanging(string value);
    partial void OnMaKhoiChanged();
    #endregion
		
		public LOPHOC()
		{
			this._NGUOIDUNGs = new EntitySet<NGUOIDUNG>(new Action<NGUOIDUNG>(this.attach_NGUOIDUNGs), new Action<NGUOIDUNG>(this.detach_NGUOIDUNGs));
			this._KHOI = default(EntityRef<KHOI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLop", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLop
		{
			get
			{
				return this._MaLop;
			}
			set
			{
				if ((this._MaLop != value))
				{
					this.OnMaLopChanging(value);
					this.SendPropertyChanging();
					this._MaLop = value;
					this.SendPropertyChanged("MaLop");
					this.OnMaLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLop", DbType="NVarChar(50)")]
		public string TenLop
		{
			get
			{
				return this._TenLop;
			}
			set
			{
				if ((this._TenLop != value))
				{
					this.OnTenLopChanging(value);
					this.SendPropertyChanging();
					this._TenLop = value;
					this.SendPropertyChanged("TenLop");
					this.OnTenLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhoi", DbType="Char(10)")]
		public string MaKhoi
		{
			get
			{
				return this._MaKhoi;
			}
			set
			{
				if ((this._MaKhoi != value))
				{
					if (this._KHOI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhoiChanging(value);
					this.SendPropertyChanging();
					this._MaKhoi = value;
					this.SendPropertyChanged("MaKhoi");
					this.OnMaKhoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOPHOC_NGUOIDUNG", Storage="_NGUOIDUNGs", ThisKey="MaLop", OtherKey="MaLop")]
		public EntitySet<NGUOIDUNG> NGUOIDUNGs
		{
			get
			{
				return this._NGUOIDUNGs;
			}
			set
			{
				this._NGUOIDUNGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHOI_LOPHOC", Storage="_KHOI", ThisKey="MaKhoi", OtherKey="MaKhoi", IsForeignKey=true)]
		public KHOI KHOI
		{
			get
			{
				return this._KHOI.Entity;
			}
			set
			{
				KHOI previousValue = this._KHOI.Entity;
				if (((previousValue != value) 
							|| (this._KHOI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHOI.Entity = null;
						previousValue.LOPHOCs.Remove(this);
					}
					this._KHOI.Entity = value;
					if ((value != null))
					{
						value.LOPHOCs.Add(this);
						this._MaKhoi = value.MaKhoi;
					}
					else
					{
						this._MaKhoi = default(string);
					}
					this.SendPropertyChanged("KHOI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NGUOIDUNGs(NGUOIDUNG entity)
		{
			this.SendPropertyChanging();
			entity.LOPHOC = this;
		}
		
		private void detach_NGUOIDUNGs(NGUOIDUNG entity)
		{
			this.SendPropertyChanging();
			entity.LOPHOC = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MONHOC")]
	public partial class MONHOC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaMonHoc;
		
		private string _TenMonHoc;
		
		private EntitySet<CAUHOI> _CAUHOIs;
		
		private EntitySet<DETHI> _DETHIs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaMonHocChanging(string value);
    partial void OnMaMonHocChanged();
    partial void OnTenMonHocChanging(string value);
    partial void OnTenMonHocChanged();
    #endregion
		
		public MONHOC()
		{
			this._CAUHOIs = new EntitySet<CAUHOI>(new Action<CAUHOI>(this.attach_CAUHOIs), new Action<CAUHOI>(this.detach_CAUHOIs));
			this._DETHIs = new EntitySet<DETHI>(new Action<DETHI>(this.attach_DETHIs), new Action<DETHI>(this.detach_DETHIs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMonHoc", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaMonHoc
		{
			get
			{
				return this._MaMonHoc;
			}
			set
			{
				if ((this._MaMonHoc != value))
				{
					this.OnMaMonHocChanging(value);
					this.SendPropertyChanging();
					this._MaMonHoc = value;
					this.SendPropertyChanged("MaMonHoc");
					this.OnMaMonHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMonHoc", DbType="NVarChar(50)")]
		public string TenMonHoc
		{
			get
			{
				return this._TenMonHoc;
			}
			set
			{
				if ((this._TenMonHoc != value))
				{
					this.OnTenMonHocChanging(value);
					this.SendPropertyChanging();
					this._TenMonHoc = value;
					this.SendPropertyChanged("TenMonHoc");
					this.OnTenMonHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MONHOC_CAUHOI", Storage="_CAUHOIs", ThisKey="MaMonHoc", OtherKey="MaMonHoc")]
		public EntitySet<CAUHOI> CAUHOIs
		{
			get
			{
				return this._CAUHOIs;
			}
			set
			{
				this._CAUHOIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MONHOC_DETHI", Storage="_DETHIs", ThisKey="MaMonHoc", OtherKey="MaMonHoc")]
		public EntitySet<DETHI> DETHIs
		{
			get
			{
				return this._DETHIs;
			}
			set
			{
				this._DETHIs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CAUHOIs(CAUHOI entity)
		{
			this.SendPropertyChanging();
			entity.MONHOC = this;
		}
		
		private void detach_CAUHOIs(CAUHOI entity)
		{
			this.SendPropertyChanging();
			entity.MONHOC = null;
		}
		
		private void attach_DETHIs(DETHI entity)
		{
			this.SendPropertyChanging();
			entity.MONHOC = this;
		}
		
		private void detach_DETHIs(DETHI entity)
		{
			this.SendPropertyChanging();
			entity.MONHOC = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NGUOIDUNG")]
	public partial class NGUOIDUNG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TaiKhoan;
		
		private string _MatKhau;
		
		private string _MaPhanQuyen;
		
		private string _MaKhoi;
		
		private string _MaLop;
		
		private string _HoTen;
		
		private string _CMND_TCC;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _SoDienThoai;
		
		private string _Email;
		
		private EntitySet<DANHSACHTHISINH> _DANHSACHTHISINHs;
		
		private EntitySet<KETQUATHI> _KETQUATHIs;
		
		private EntityRef<KHOI> _KHOI;
		
		private EntityRef<LOPHOC> _LOPHOC;
		
		private EntityRef<PHANQUYEN> _PHANQUYEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTaiKhoanChanging(string value);
    partial void OnTaiKhoanChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnMaPhanQuyenChanging(string value);
    partial void OnMaPhanQuyenChanged();
    partial void OnMaKhoiChanging(string value);
    partial void OnMaKhoiChanged();
    partial void OnMaLopChanging(string value);
    partial void OnMaLopChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnCMND_TCCChanging(string value);
    partial void OnCMND_TCCChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public NGUOIDUNG()
		{
			this._DANHSACHTHISINHs = new EntitySet<DANHSACHTHISINH>(new Action<DANHSACHTHISINH>(this.attach_DANHSACHTHISINHs), new Action<DANHSACHTHISINH>(this.detach_DANHSACHTHISINHs));
			this._KETQUATHIs = new EntitySet<KETQUATHI>(new Action<KETQUATHI>(this.attach_KETQUATHIs), new Action<KETQUATHI>(this.detach_KETQUATHIs));
			this._KHOI = default(EntityRef<KHOI>);
			this._LOPHOC = default(EntityRef<LOPHOC>);
			this._PHANQUYEN = default(EntityRef<PHANQUYEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoan", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TaiKhoan
		{
			get
			{
				return this._TaiKhoan;
			}
			set
			{
				if ((this._TaiKhoan != value))
				{
					this.OnTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoan = value;
					this.SendPropertyChanged("TaiKhoan");
					this.OnTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhanQuyen", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MaPhanQuyen
		{
			get
			{
				return this._MaPhanQuyen;
			}
			set
			{
				if ((this._MaPhanQuyen != value))
				{
					if (this._PHANQUYEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPhanQuyenChanging(value);
					this.SendPropertyChanging();
					this._MaPhanQuyen = value;
					this.SendPropertyChanged("MaPhanQuyen");
					this.OnMaPhanQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhoi", DbType="Char(10)")]
		public string MaKhoi
		{
			get
			{
				return this._MaKhoi;
			}
			set
			{
				if ((this._MaKhoi != value))
				{
					if (this._KHOI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhoiChanging(value);
					this.SendPropertyChanging();
					this._MaKhoi = value;
					this.SendPropertyChanged("MaKhoi");
					this.OnMaKhoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLop", DbType="Char(10)")]
		public string MaLop
		{
			get
			{
				return this._MaLop;
			}
			set
			{
				if ((this._MaLop != value))
				{
					if (this._LOPHOC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLopChanging(value);
					this.SendPropertyChanging();
					this._MaLop = value;
					this.SendPropertyChanged("MaLop");
					this.OnMaLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND_TCC", DbType="Char(12)")]
		public string CMND_TCC
		{
			get
			{
				return this._CMND_TCC;
			}
			set
			{
				if ((this._CMND_TCC != value))
				{
					this.OnCMND_TCCChanging(value);
					this.SendPropertyChanging();
					this._CMND_TCC = value;
					this.SendPropertyChanged("CMND_TCC");
					this.OnCMND_TCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="Char(11)")]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NGUOIDUNG_DANHSACHTHISINH", Storage="_DANHSACHTHISINHs", ThisKey="TaiKhoan", OtherKey="TaiKhoan")]
		public EntitySet<DANHSACHTHISINH> DANHSACHTHISINHs
		{
			get
			{
				return this._DANHSACHTHISINHs;
			}
			set
			{
				this._DANHSACHTHISINHs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NGUOIDUNG_KETQUATHI", Storage="_KETQUATHIs", ThisKey="TaiKhoan", OtherKey="TaiKhoan")]
		public EntitySet<KETQUATHI> KETQUATHIs
		{
			get
			{
				return this._KETQUATHIs;
			}
			set
			{
				this._KETQUATHIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHOI_NGUOIDUNG", Storage="_KHOI", ThisKey="MaKhoi", OtherKey="MaKhoi", IsForeignKey=true)]
		public KHOI KHOI
		{
			get
			{
				return this._KHOI.Entity;
			}
			set
			{
				KHOI previousValue = this._KHOI.Entity;
				if (((previousValue != value) 
							|| (this._KHOI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHOI.Entity = null;
						previousValue.NGUOIDUNGs.Remove(this);
					}
					this._KHOI.Entity = value;
					if ((value != null))
					{
						value.NGUOIDUNGs.Add(this);
						this._MaKhoi = value.MaKhoi;
					}
					else
					{
						this._MaKhoi = default(string);
					}
					this.SendPropertyChanged("KHOI");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOPHOC_NGUOIDUNG", Storage="_LOPHOC", ThisKey="MaLop", OtherKey="MaLop", IsForeignKey=true)]
		public LOPHOC LOPHOC
		{
			get
			{
				return this._LOPHOC.Entity;
			}
			set
			{
				LOPHOC previousValue = this._LOPHOC.Entity;
				if (((previousValue != value) 
							|| (this._LOPHOC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOPHOC.Entity = null;
						previousValue.NGUOIDUNGs.Remove(this);
					}
					this._LOPHOC.Entity = value;
					if ((value != null))
					{
						value.NGUOIDUNGs.Add(this);
						this._MaLop = value.MaLop;
					}
					else
					{
						this._MaLop = default(string);
					}
					this.SendPropertyChanged("LOPHOC");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHANQUYEN_NGUOIDUNG", Storage="_PHANQUYEN", ThisKey="MaPhanQuyen", OtherKey="MaPhanQuyen", IsForeignKey=true)]
		public PHANQUYEN PHANQUYEN
		{
			get
			{
				return this._PHANQUYEN.Entity;
			}
			set
			{
				PHANQUYEN previousValue = this._PHANQUYEN.Entity;
				if (((previousValue != value) 
							|| (this._PHANQUYEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHANQUYEN.Entity = null;
						previousValue.NGUOIDUNGs.Remove(this);
					}
					this._PHANQUYEN.Entity = value;
					if ((value != null))
					{
						value.NGUOIDUNGs.Add(this);
						this._MaPhanQuyen = value.MaPhanQuyen;
					}
					else
					{
						this._MaPhanQuyen = default(string);
					}
					this.SendPropertyChanged("PHANQUYEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DANHSACHTHISINHs(DANHSACHTHISINH entity)
		{
			this.SendPropertyChanging();
			entity.NGUOIDUNG = this;
		}
		
		private void detach_DANHSACHTHISINHs(DANHSACHTHISINH entity)
		{
			this.SendPropertyChanging();
			entity.NGUOIDUNG = null;
		}
		
		private void attach_KETQUATHIs(KETQUATHI entity)
		{
			this.SendPropertyChanging();
			entity.NGUOIDUNG = this;
		}
		
		private void detach_KETQUATHIs(KETQUATHI entity)
		{
			this.SendPropertyChanging();
			entity.NGUOIDUNG = null;
		}
	}
}
#pragma warning restore 1591
